//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.16 at 08:03:52 PM CEST 
//


package org.kaleta.accountant.backend.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clazz"
})
@XmlRootElement(name = "schema")
public class Schema {

    @XmlElement(name = "class", required = true)
    protected List<Schema.Class> clazz;

    public List<Schema.Class> getClazz() {
        if (clazz == null) {
            clazz = new ArrayList<>();
        }
        return this.clazz;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "group"
    })
    public static class Class {

        protected List<Schema.Class.Group> group;
        @XmlAttribute(name = "id", required = true)
        protected String id ="";
        @XmlAttribute(name = "name", required = true)
        protected String name = "";

        public List<Schema.Class.Group> getGroup() {
            if (group == null) {
                group = new ArrayList<>();
            }
            return this.group;
        }

        public String getId() {
            return id;
        }

        public void setId(String value) {
            this.id = value;
        }

        public String getName() {
            return name;
        }

        public void setName(String value) {
            this.name = value;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "account"
        })
        public static class Group {

            protected List<Schema.Class.Group.Account> account;
            @XmlAttribute(name = "id", required = true)
            protected String id = "";
            @XmlAttribute(name = "name", required = true)
            protected String name = "";

            public List<Schema.Class.Group.Account> getAccount() {
                if (account == null) {
                    account = new ArrayList<>();
                }
                return this.account;
            }

            public String getId() {
                return id;
            }

            public void setId(String value) {
                this.id = value;
            }

            public String getName() {
                return name;
            }

            public void setName(String value) {
                this.name = value;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Account {

                @XmlAttribute(name = "id", required = true)
                protected String id = "";
                @XmlAttribute(name = "name", required = true)
                protected String name = "";
                @XmlAttribute(name = "type", required = true)
                protected String type = "";

                public String getId() {
                    return id;
                }

                public void setId(String value) {
                    this.id = value;
                }

                public String getName() {
                    return name;
                }

                public void setName(String value) {
                    this.name = value;
                }

                public String getType() {
                    return type;
                }

                public void setType(String value) {
                    this.type = value;
                }

            }

        }

    }

}
