//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 02:33:32 AM CET 
//


package org.kaleta.accountant.backend.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "row"
})
@XmlRootElement(name = "budget")
public class BudgetModel {

    protected List<Row> row;
    @XmlAttribute(name = "year", required = true)
    protected String year;

    public BudgetModel() {
    }

    public BudgetModel(BudgetModel budgetModel) {
        this.setYear(budgetModel.getYear());
        for (Row row : budgetModel.getRow()){
            this.getRow().add(new Row(row));
        }
    }

    public List<Row> getRow() {
        if (row == null) {
            row = new ArrayList<Row>();
        }
        return this.row;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String value) {
        this.year = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "month"
    })
    public static class Row {

        @XmlElement(required = true)
        protected List<Month> month;
        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "type", required = true)
        protected String type;
        @XmlAttribute(name = "name", required = true)
        protected String name;

        public Row() {
        }

        public Row(Row row) {
            this.setId(row.getId());
            this.setName(row.getName());
            this.setType(row.getType());
            for (Month month : row.getMonth()){
                this.getMonth().add(new Month(month));
            }
        }

        public Row(String id, String type, String name, List<Month> months) {
            this.setId(id);
            this.setType(type);
            this.setName(name);
            this.getMonth().addAll(months);
        }

        public List<Month> getMonth() {
            if (month == null) {
                month = new ArrayList<Month>();
            }
            return this.month;
        }

        public String getId() {
            return id;
        }

        public void setId(String value) {
            this.id = value;
        }

        public String getType() {
            return type;
        }

        public void setType(String value) {
            this.type = value;
        }

        public String getName() {
            return name;
        }

        public void setName(String value) {
            this.name = value;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Month {

            @XmlAttribute(name = "number", required = true)
            protected String number;
            @XmlAttribute(name = "value", required = true)
            protected String value;

            public Month() {
            }

            public Month(Month month) {
                this.setNumber(month.getNumber());
                this.setValue(month.getValue());
            }

            public String getNumber() {
                return number;
            }

            public void setNumber(String value) {
                this.number = value;
            }

            public String getValue() {
                return value;
            }

            public void setValue(String value) {
                this.value = value;
            }

        }

    }

}
